### PR TITLE
PAAS-2315: fix Jahia jCustomer unlink issue

### PR DESCRIPTION
**Pull request by julien-gagnon**
JIRA issue: https://jira.jahia.org/browse/PAAS-2315

Short description:
Add the removeKibanaDashboardAccountsAndSpace action to make sure everything kibana related is deleted when unlinking.

### CODE REVIEW

**Comment by julien-gagnon** [comment]
I preferred to not call removeKibanaDashboardAccountsAndSpace in the removeAndCleanJexperience action because I was worried this could break it's usage in common/restore.yml restoreJahia action.

**Comment by laurentfufu** [comment]
As this action will failed if the jcustomer env is stopped, perhaps it would be better to test the status of the jcustomer environment beforehand so that you can eventually start it before running the `removeKibanaDashboardAccountsAndSpace` action and then stop it again if necessary.

I guess we never use them but there is endpoint for that: https://docs.jelastic.com/api/7.3.2/public/#!/api/environment.Control-method-StartEnv and https://docs.jelastic.com/api/7.3.2/public/#!/api/environment.Control-method-StopEnv

**Comment by laurentfufu** [comment]
indeed if the jcustomer env is stopped, it looks like the manifest fails unless the isUnomiEnvDeletion setting is true.

**Comment by julien-gagnon** [comment]
@kevinvandel here is the check we talked about this morning.

**Review by kevinvandel — APPROVED** [review]

**Review by laurentfufu — APPROVED** [review]

**Pull request merged**
