### PR TITLE
PAAS-2132: Increase jdbc maxAge setting from 5min to 15min

### PR DESCRIPTION
**Pull request by Ronan-Gorain**
JIRA issue: https://jira.jahia.org/browse/PAAS-2132

Short description:

### CODE REVIEW

**Review by kevinvandel — CHANGES_REQUESTED** [review]
Shouldn't an action b added to the migration package to update existing envs ?

**Comment by Ronan-Gorain** [comment]
It should be updated by events. Maybe I should mention it with a comment in the package

**Comment by kevinvandel** [comment]
@Ronan-Gorain I was talking about the `maxAge` update in `context.xml` (cf. https://github.com/Jahia/jahiastic-jahia/pull/210)

**Comment by Ronan-Gorain** [comment]
My bad. Done

**Review by kevinvandel — APPROVED** [review]

**Pull request merged**
